import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  globalLoader: {
    isLoading: false,
    message: 'Preparing your workspace...',
  },
  alerts: [], // Array to support stacking multiple alerts
};

const uiSlice = createSlice({
  name: 'ui',
  initialState,
  reducers: {
    showLoader: (state, action) => {
      state.globalLoader.isLoading = true;
      if (action.payload) {
        state.globalLoader.message = action.payload;
      }
    },
    hideLoader: (state) => {
      state.globalLoader.isLoading = false;
    },
    showAlert: (state, action) => {
      // payload expects: { id, type, message, duration? }
      // id should be generated by the dispatching thunk/action to ensure uniqueness, or we handle it here if not passed
      state.alerts.push(action.payload);
    },
    removeAlert: (state, action) => {
      // payload expects: id
      state.alerts = state.alerts.filter((alert) => alert.id !== action.payload);
    },
  },
});

export const { showLoader, hideLoader, showAlert, removeAlert } = uiSlice.actions;

export default uiSlice.reducer;
